### ISSUE TITLE
Latest B40 Release of Jammy CLI does not bring up ethernet by default

### ISSUE THREAD

**Issue by tduffy83** [radxa-build/rockpi-s#2]
The image installs fine and boots (blue blinking light), but upon connecting an ethernet cable a connection is not made.  Neither ethernet LEDs light up either.  The Bookworm CLI image does work by default with ethernet.

After further investigation using serial console, the eth0 interface is nowhere to be found, and I have not found a workaround yet.

EDIT:  I have two Rock Pi S boards, both version 1.3, but only one of them is the S variant.  The S variant fails to boot Ubuntu at all, which I am attributing to having installed on NAND.  The S variant will boot into Ubuntu if installed on SD card.

**Comment by RadxaMitchell** [comment]
Hi, @tduffy83 What is the size of your SD Nand ?

**Comment by RadxaYuntian** [comment]
Ubuntu is currently not supported and only provided AS-IS. My guess is that `netplan` is causing problems.

**Comment by tduffy83** [comment]
It's the 8gb nand.

I will check netplan.  Otherwise will use armbian.

Not expecting any support, just wanted to make you guys aware in case you wanted to look into it for next release.

**Comment by RadxaYuntian** [comment]
We will drop Ubuntu image in the future and focus solely on what we have tested.

**Comment by WiFiLocalization** [comment]
@RadxaYuntian 
What are the difference between the debian cli and the armbian images?

**Comment by RadxaYuntian** [comment]
Armbian is produced by 3rd party and is based on Debian and Ubuntu. Our Debian CLI image is not related to Armbian since we have our own build system.

I'll lock this issue since it is unrelated to the original problem. If you have more questions, feel free to ask in our forum or Discord.
